# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
