# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170405_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
