# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170405_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='Category',
            new_name='category',
        ),
    ]
